### ISSUE TITLE
Spigot 1.8+

### ISSUE THREAD

**Issue by Carton32** [tobiyas/Enderdragonsplus#1]
Hi,

Are planning to update your plugin ?

I can make a donation if you can update your resource.

Thank you for your answer

Carton__

**Comment by minetonight** [comment]
Same question but for 1.9. I cant get to make Utils compile, in order to see if there is any chance in the SpigotAPI to get dragons for a ride.

**Comment by tobiyas** [comment]
Yes, it's possible. ;) Even did it for private use.
I'll think about publishing it.
